apiVersion: v1
kind: Service
metadata:
  name: nextjs-monitor
  namespace: dev   # ← ЭНД ЗААВАЛ НЭМ
spec:
  type: NodePort
  selector:
    app: nextjs-monitor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080   # Хэвээр үлдээ, гаднаас хандах порт
